### ISSUE TITLE
Wiki query pagination

### ISSUE THREAD

**Issue by stinodes** [MitchBarnett/wiki-bank-tag-integration#16] opened 2023-12-22 23:30 UTC
I've seen mention of the wiki's 5000-items query limit, but the current queries seem limited to 2000 items.
Changes to either fully support pagination, or at least grow the default, could be great.

**Comment by MitchBarnett** [comment] 2024-10-16 18:15
Duplicate of #9 tracking there.

**Closed by MitchBarnett** 2024-10-16 18:15 UTC
